// -------------------------------------------------- //
// This file is autogenerated by pioasm; do not edit! //
// -------------------------------------------------- //

#pragma once

#if !PICO_NO_HARDWARE
#include "hardware/pio.h"
#endif

// ------------ //
// quad_encoder //
// ------------ //

#define quad_encoder_wrap_target 0
#define quad_encoder_wrap 0

static const uint16_t quad_encoder_program_instructions[] = {
            //     .wrap_target
    0x4002, //  0: in     pins, 2                    
            //     .wrap
};

#if !PICO_NO_HARDWARE
static const struct pio_program quad_encoder_program = {
    .instructions = quad_encoder_program_instructions,
    .length = 1,
    .origin = -1,
};

static inline pio_sm_config quad_encoder_program_get_default_config(uint offset) {
    pio_sm_config c = pio_get_default_sm_config();
    sm_config_set_wrap(&c, offset + quad_encoder_wrap_target, offset + quad_encoder_wrap);
    return c;
}
#endif

